development:
  adapter: postgresql
  encoding: unicode
  database: adeca_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: adeca_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: adeca_production
  pool: 5
  username:
  password:
